config/routes.rb
Rails.application.routes.draw do
  root "pages#login"
  
  ##################
  ##################
  ####          ####
  ####   post   ####
  ####          ####
  ##################
  ##################

  post "login" => "sessions#authenticate", as: "login"
  post "request/join" => "requests#join", as: "join_group"

  ##################
  ##################
  ####          ####
  ####   get    ####
  ####          ####
  ##################
  ##################
  
  get "/home" => "pages#index", as: "pages_index"
  get "request/accept/:user_id/group/:group_id" => "requests#accept", as: "accept_request"
  get "requests/:code" => "requests#show", as: "request"

  ##################
  ##################
  ####          ####
  ####   delete ####
  ####          ####
  ##################
  ##################

  delete "/logout" => "sessions#destroy", as: "logout"

  resources :users, except: [:index, :new] do
    with_scope_level(:new) do
      get 'new/:role' => "users#new", as: ''
    end
  end

  resources :groups do
    resources :posts, except: [:index]
  end
  resources :documents, only: [:index, :create, :destroy]
  resources :video_repositories do
    resources :videos, only: [:show, :create, :destroy]
  end
end

app/models/video_repository.rb
class VideoRepository
  include Mongoid::Document

  field :title, type: String

  belongs_to :user
  has_many :videos
  accepts_nested_attributes_for :videos, allow_destroy: true
end

app/controllers/video_repositories_controller.rb
class VideoRepositoriesController < ApplicationController
  before_filter :admin?
  def create
    repo = current_user.video_repositories.create!(data)
    redirect_to video_repository_path(repo.id),notice: "Video repository created successfuly"
  end

  def show
    @repo = VideoRepository.find(params[:id])
    @video = @repo.videos.new
  end

  private

  def data
    params.require(:video_repository).permit(:title)
  end
end

app/helpers/video_repositories_helper.rb
module VideoRepositoriesHelper
end

app/views/video_repositories/show.html.haml
.ui.segment
  %h3.ui.header
    =@repo.title.titleize
  .ui.error.message#video-warning
    =semantic_icon 'close'
    .header
      MP4 and OGG are the only available video files type that can be uploaded
  .ui.form
    =form_for [@repo, @video], remote:true, html: {multipart: true} do |v|
      =v.file_field :video, data: {multiple_caption: "{count} files selected"}, class: 'input-field'
      %label#video_button{for: 'video_video'}
        %span Choose a video file
      =v.submit "Upload", class: "ui button green"
  .ui.divided.list
    -@repo.videos.all.each do |video|
      .item
        =link_to video_repository_video_path(@repo, video.id) , data:{confirm: "Are you sure you want to delete this video?", method: :delete} do
          .right.floated.compact.ui.button.red.inverted
            Remove
        =link_to video_repository_video_path(@repo , video.id)  do
          .right.floated.compact.ui.button.green.inverted
            View
        = video.video.thumb.url.present? ? (image_tag video.video.thumb.url , class: "ui avatar image") : (image_tag "7.jpg" , class: "ui avatar image")
        .content
          =link_to video.title, video_repository_video_path(@repo , video.id) , class: "header" 