config/routes.rb
Rails.application.routes.draw do
  root "pages#login"
  
  ##################
  ##################
  ####          ####
  ####   post   ####
  ####          ####
  ##################
  ##################

  post "login" => "sessions#authenticate", as: "login"
  post "request/join" => "requests#join", as: "join_group"

  ##################
  ##################
  ####          ####
  ####   get    ####
  ####          ####
  ##################
  ##################
  
  get "/home" => "pages#index", as: "pages_index"
  get "request/accept/:user_id/group/:group_id" => "requests#accept", as: "accept_request"
  get "requests/:code" => "requests#show", as: "request"

  ##################
  ##################
  ####          ####
  ####   delete ####
  ####          ####
  ##################
  ##################

  delete "/logout" => "sessions#destroy", as: "logout"

  resources :users, except: [:index, :new] do
    with_scope_level(:new) do
      get 'new/:role' => "users#new", as: ''
    end
  end

  resources :groups do
    resources :posts, except: [:index]
  end
  resources :documents, only: [:index, :create, :destroy]
  resources :video_repositories do
    resources :videos, only: [:show, :create, :destroy]
  end
end

app/models/request.rb
class Request
  include Mongoid::Document

  field :token, type: String

  belongs_to :user
  accepts_nested_attributes_for:user
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_filter :admin?, except: [:join]
  def join
    code = params[:code] || ""
    if Group.where(token: code).present?
      group = Group.find_by_token(code)
    end
    if !Group.where(token: code).present?
      redirect_to pages_index_path, notice: "Group doesn't exist yet"
    elsif current_user.requests.where(token: code).present?
      redirect_to pages_index_path, notice: "You already sent a request"
    elsif User.where(email: current_user.email, student_of: group.id).present?
      redirect_to pages_index_path, notice: "You're already part of the group"
    else
      current_user.requests.create(token: params[:code])
      redirect_to pages_index_path, notice: "Request Sent"
    end
  end

  def accept
    if User.addGroup(params[:user_id], params[:group_id])
      Request.where(user_id: params[:user_id],token: params[:group_id]).delete
      redirect_to group_path(params[:group_id]),notice: "Student added in the group"
    end
  end

  def show
    @group = Group.find_by_token params[:code]
  end

  private

  def data
    params.require(:request).permit(:code)
  end

end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/show.html.haml
=render 'groups/sub_menu'
.ui.segment
  -if !Request.where(token: params[:code]).present?
    %h4.center.align.header
      No Request at the moment
  -Request.where(token: params[:code]).each do |r|
    .item
      =link_to "javascript:;", data: {method: :delete, confirm: "Do you really want to decline this request?"} do
        .ui.basic.red.button.right.floated.compact#decline-button
          Decline
      =link_to accept_request_path(r.user_id.to_s, r.token) do
        .ui.basic.green.button.right.floated.compact#accept-button
          Accept
      .content
        .header
          =r.user.fullname
          want to joint the group