config/routes.rb
Rails.application.routes.draw do
  root "pages#login"
  
  ##################
  ##################
  ####          ####
  ####   post   ####
  ####          ####
  ##################
  ##################

  post "login" => "sessions#authenticate", as: "login"
  post "request/join" => "requests#join", as: "join_group"

  ##################
  ##################
  ####          ####
  ####   get    ####
  ####          ####
  ##################
  ##################
  
  get "/home" => "pages#index", as: "pages_index"
  get "request/accept/:user_id/group/:group_id" => "requests#accept", as: "accept_request"
  get "requests/:code" => "requests#show", as: "request"

  ##################
  ##################
  ####          ####
  ####   delete ####
  ####          ####
  ##################
  ##################

  delete "/logout" => "sessions#destroy", as: "logout"

  resources :users, except: [:index, :new] do
    with_scope_level(:new) do
      get 'new/:role' => "users#new", as: ''
    end
  end

  resources :groups do
    resources :posts, except: [:index]
  end
  resources :documents, only: [:index, :create, :destroy]
  resources :video_repositories do
    resources :videos, only: [:show, :create, :destroy]
  end
end

app/views/pages/index.html.haml
=render 'sub_menu'

app/views/pages/login.html.haml
#login-container
  %h2.ui.center.aligned.header#login-label
    Login
  =form_tag login_path, method: :post, class: 'ui form', id: "login-form-control" do
    .field.required.login-field
      =text_field_tag :email, nil, placeholder: "E-mail"
    .field.required.login-field
      =password_field_tag :password, nil, placeholder: "Password"
    .two.fields
      .field
        .ui.checkbox
          =check_box :remember, nil
          %label 
            Remember Me
      .field
        =link_to "Forgot Password", "javascript:;", class: "link"
    .two.fields
      .field
        =submit_tag "Login", class: "ui green button large login-buttons"
      .field
        .ui.large.standard.option.button.login-buttons#sign-up-button
          Sign Up
.ui.small.option.modal#sign-up-modal
  .ui.top.attached.label
    Sign up as
  .ui.buttons#role-choices
    =link_to "Student", new_user_path("student"), class: "ui green button role-choice"
    .or
    =link_to "Instructor", new_user_path("instructor"), class: "ui green button role-choice"