config/routes.rb
Rails.application.routes.draw do
  root "pages#login"
  
  ##################
  ##################
  ####          ####
  ####   post   ####
  ####          ####
  ##################
  ##################

  post "login" => "sessions#authenticate", as: "login"
  post "request/join" => "requests#join", as: "join_group"

  ##################
  ##################
  ####          ####
  ####   get    ####
  ####          ####
  ##################
  ##################
  
  get "/home" => "pages#index", as: "pages_index"
  get "request/accept/:user_id/group/:group_id" => "requests#accept", as: "accept_request"
  get "requests/:code" => "requests#show", as: "request"

  ##################
  ##################
  ####          ####
  ####   delete ####
  ####          ####
  ##################
  ##################

  delete "/logout" => "sessions#destroy", as: "logout"

  resources :users, except: [:index, :new] do
    with_scope_level(:new) do
      get 'new/:role' => "users#new", as: ''
    end
  end

  resources :groups do
    resources :posts, except: [:index]
  end
  resources :documents, only: [:index, :create, :destroy]
  resources :video_repositories do
    resources :videos, only: [:show, :create, :destroy]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def authenticated?
    if !logged_in?
      redirect_to root_url
    end
  end

  def check_if_logged_in
    if logged_in?
      redirect_to pages_index_path
    end
  end

  def admin?
    if current_user.role == 'student'
      redirect_to pages_index_path, notice: "Unkown URL"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def has_extra(quiz,homework,downloadable_resources, post_link)
    content_tag :div, class: "extra" do
      if quiz || homework || downloadable_resources
        concat "Has: "
      end
      if quiz
        concat content_tag :div, "Quiz", class: "ui label"
      end
      if homework
        concat content_tag :div, "Homework", class: "ui label"
       end
      if downloadable_resources
        concat content_tag :div, "Downloadable Resources", class: "ui label"
      end
      concat content_tag :a, "View Post", class: "ui button green right floated", href: post_link
    end
  end
end

app/views/application/_footer.html.haml
-if logged_in?
  -if current_user.role != 'student'
    .ui.small.modal#create-group-modal
      .ui.top.attached.label
        Create Group
      .ui.form#create-group-form-control
        =form_for Group.new do |g|
          .field
            =g.text_field :title, placeholder: "Group Title"
          .field
            =g.text_area :description, placeholder: "Group Description"
          .field
            =g.submit "Create Group", class: "ui button green"
    .ui.small.modal#create-video-repository-modal
      .ui.top.attached.label
        Create Video Repository
      .ui.form#create-group-form-control
        =form_for current_user.video_repositories.new do |g|
          .field
            =g.text_field :title, placeholder: "Video Repository Title"
          .field
            =g.submit "Create Video Repository", class: "ui button green"
      

app/views/application/_header.html.haml
.top-bar
  .ui.grid.container
    .row
      .four.wide.column
        %h4.brand-name
          Brand Name
      -if logged_in?
        .right.floated.four.wide.column
          .ui.text-right
            .ui.horizontal.list.inverted
              =link_to "Home", pages_index_path, class: "item"
              =link_to "#{current_user.fullname}", edit_user_path(current_user.id), class: "item"
            .ui.icon.top.right.pointing.dropdown#main_setting
              =semantic_icon 'inverted large setting'
              .menu
                -if current_user.role != 'student'
                  =link_to documents_path, class: "item", id: "my-file-repository" do
                    =semantic_icon 'file'
                    My File Repository
                  =link_to "javascript:;", class: "item", id: "my-video-repository" do
                    =semantic_icon 'folder'
                    My Video Repositories
                  .divider
                  =link_to "javascript:;", class: "item", id: "create-video-repository" do
                    =semantic_icon 'video play'
                    Create Video Repository
                  =link_to "javascript:;", class: "item", id: "create-group" do
                    =semantic_icon "users"
                    Create Group
                .divider
                =link_to logout_path, method: :delete, class: "item" do
                  =semantic_icon "power"
                  Logout

app/views/application/_left_sidebar.html.haml
-if current_user.role == "student"
  .ui.segment
    .ui.top.attached.label
      Join group
    .content
      .ui.form.join-form-control
        =form_tag join_group_path, method: :post do 
          =text_field_tag :code, nil, placeholder: "Input group code here"
          =submit_tag "Join group", class: "ui button green", id: "join-button"
-else
  .ui.segment
    .ui.top.attached.label
      Repositories
    .content
      .ui.link.list
        -current_user.video_repositories.each do |r|
          =link_to r.title.titleize, video_repository_path(r.id), class: "item"

app/views/application/_sub_menu.html.haml
.overlay#sub_menu
  .ui.menu
    =link_to pages_index_path, class: ((params[:controller] == 'pages' and params[:action] == 'index') ? "item active" : "item" )do
      Home
    =link_to groups_path, class: ((params[:controller] == 'groups' and params[:action] == 'index') ? "item active" : "item" )do
      Groups